blueprint:
  name: YAFN - Yet Another Double Take Notifications - v0.5.1
  description: |
    ### [Yet Another Double Take Notifications - v0.5.1](https://github.com/ralphv/yafn)
  domain: automation
  input:
    input_double_take_base_url:
      name: Double take base url
      description: This is the base url of your double take.
      selector:
        text:
          prefix: URL
          type: url
    notify_device:
      name: Mobile Device
      description: |
        Select a device that runs the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
    silence_timer:
      name: The silence timer
      description: The time to silence the notifications in minutes.
      default: 30
      selector:
        number:
          min: 5
          max: 1440
          unit_of_measurement: "minutes"
    alert_google_sdk:
      name: Broadcast to google assistant
      description: Announces on google assistant
      default: false
      selector:
        boolean:
    include_persons_filter:
      name: Include Persons Filter
      description: |
        Enter or select one person at a time.
        If left empty, it will allow all persons.
      default: ""
      selector:
        select:
          multiple: true
          custom_value: true
    exclude_persons_filter:
      name: Exclude Persons Filter
      description: |
        Enter or select one person at a time.
        If left empty, it will not exclude any persons.
      default: ""
      selector:
        select:
          multiple: true
          custom_value: true

trigger:
  - platform: mqtt
    id: double-take-matches
    topic: double-take/matches/+
action:
  - choose:
      - alias: Double take new match
        conditions:
          - condition: trigger
            id: double-take-matches
          - condition: template
            alias: "include persons filter"
            value_template: >-
              {{ not include_persons_filter|length or trigger.payload_json.match.name in include_persons_filter }}
          - condition: template
            alias: "exclude persons filter"
            value_template: >-
              {{ not exclude_persons_filter|length or trigger.payload_json.match.name not in exclude_persons_filter }}
        sequence:
          - variables:
              event_id: "{{ trigger.payload_json.id }}"
              camera: "{{ trigger.payload_json.camera }}"
              person: "{{ trigger.payload_json.match.name }}"
              confidence: "{{ trigger.payload_json.match.confidence }}"
              match: "{{ trigger.payload_json.match.match }}"
              filename: "{{ trigger.payload_json.match.filename }}"
              action_open_image: "{{double_take_base_url}}/api/storage/matches/{{filename}}"
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            message: "{{ person }} detected on {{ camera }}"
            data:
              tag: "{{ event_id }}"
              image: "{{action_open_image}}"
              clickAction: "{{action_open_image}}"
              notification_icon: mdi:person
              channel: "{{camera}}-{{person}}-double-take"
          - choose:
              - alias: Broadcast to google
                conditions:
                  - condition: template
                    value_template: "{{ alert_google_sdk }}"
                sequence:
                  - service: notify.google_assistant_sdk
                    data:
                      message: "{{ person }} detected on {{ camera }}"

variables:
  input_double_take_base_url: !input input_double_take_base_url
  double_take_base_url: "{{ input_double_take_base_url.rstrip('/')}}"
  silence_timer: !input silence_timer
  alert_google_sdk: !input alert_google_sdk
  input_include_persons_filter: !input include_persons_filter
  include_persons_filter: "{{ input_include_persons_filter | list | lower }}"
  input_exclude_persons_filter: !input exclude_persons_filter
  exclude_persons_filter: "{{ input_exclude_persons_filter | list | lower }}"

mode: parallel
